name: Deploy

on:
  push:
    branches:
      - main

jobs:
  deploy:
    timeout-minutes: 1
    runs-on: ubuntu-latest
    steps:
      - name: step1
        run: sleep 300s
      - name: step2  
        run: sleep 300s