name: Reusable Workflow

on:
  workflow_call:
    inputs:
      example-input:
        required: true
        type: string

jobs:
  example_job:
    runs-on: ubuntu-latest
    steps:
      - name: Print input
        run: "echo \"Input value: ${{ inputs.example-input }}\""